deployment:
  extraEnv:
    PGHOST:
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: PGHOST
    PGPORT:
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: PGPORT
