---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.service.extraLabels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 80
